from datetime import datetime
from typing import Optional, List
from pydantic import BaseModel, Field

# Legacy simulation schemas for compatibility
class SimulatedPaymentCreate(BaseModel):
    payer_upi_id: str = Field(default="user@okhdfcbank", description="Payer UPI ID")
    payee_upi_id: str = Field(..., description="Payee UPI ID")
    payee_name: str = Field(default="Payee", description="Payee name")
    amount: float = Field(..., gt=0, description="Payment amount in INR")
    note: Optional[str] = Field(default=None, description="Payment remark")

class PaymentDecisionUpdate(BaseModel):
    decision: str = Field(..., description="User choice: CANCELLED or CONTINUED")
    decision_reason: Optional[str] = Field(default=None, description="Reason")

class SimulatedPaymentResponse(BaseModel):
    id: int
    transaction_ref: str = "TXN-DEFAULT"
    payer_upi_id: str = "user@okhdfcbank"
    payee_upi_id: str
    payee_name: str
    amount: float
    note: Optional[str] = None
    user_decision: str = "PENDING"
    status: str = "RECORDED"
    created_at: datetime


# APP Scam Evaluation Schemas for Phase 2 & Phase 3
class PaymentAnalysisRequest(BaseModel):
    """
    Input schema for evaluating APP scam risk on an incoming payment attempt.
    """
    amount: float = Field(..., gt=0, description="Payment amount in INR")
    beneficiary: str = Field(..., min_length=1, description="Beneficiary UPI ID or name")
    new_beneficiary: bool = Field(default=False, description="True if beneficiary has never been transacted with")
    new_device: bool = Field(default=False, description="True if transaction originates from a new device/session")
    transactions_last_10_min: int = Field(default=0, ge=0, description="Count of transactions initiated in previous 10 minutes")
    previous_average: float = Field(default=0.0, ge=0.0, description="User historical average transaction amount")
    location_changed: bool = Field(default=False, description="True if geographical anomaly detected")
    unusual_time: Optional[bool] = Field(default=False, description="True if transaction occurs at an unusual time")
    transaction_time: Optional[datetime] = Field(default=None, description="Timestamp of transaction attempt")
    context_note: Optional[str] = Field(default=None, description="Optional remarks, chat prompt, or context note")


class AIAnalysisResult(BaseModel):
    """
    Structured contextual appraisal generated by Gemini AI.
    """
    available: bool = Field(default=False, description="True if Gemini contextual analysis was successfully executed")
    contextual_risk: Optional[str] = Field(default="LOW", description="LOW | MEDIUM | HIGH")
    app_indicators: List[str] = Field(default_factory=list, description="Specific contextual APP scam patterns noted by AI")
    explanation: Optional[str] = Field(default=None, description="AI plain-language explanation of risk context")
    safety_checks: List[str] = Field(default_factory=list, description="Recommended user verification steps before sending")


class PaymentAnalysisResponse(BaseModel):
    """
    Output schema for APP scam risk evaluation and decision.
    """
    transaction_id: int
    amount: float
    beneficiary: str
    risk_score: float = Field(..., ge=0.0, le=100.0, description="Computed risk score (0-100) controlled by Risk Engine")
    risk_level: str = Field(..., description="LOW | MEDIUM | HIGH")
    signals: List[str] = Field(default_factory=list, description="List of specific triggered risk indicators")
    explanation: str = Field(..., description="Plain-language explanation of detected risk indicators")
    recommended_action: str = Field(..., description="ALLOW | WARN | INTERVENE")
    ai_analysis: Optional[AIAnalysisResult] = Field(default=None, description="Gemini AI contextual appraisal & safety checks")
    created_at: datetime


# Simulated Bank Balance Schemas
class DemoAccountResponse(BaseModel):
    account_number: str = "4471"
    account_holder: str = "Rahul Sharma"
    available_balance: float
    currency: str = "INR"
    is_demo: bool = True


class PaymentConfirmationRequest(BaseModel):
    transaction_id: Optional[int] = None
    amount: float = Field(..., gt=0, description="Amount to deduct upon confirmation")


class PaymentConfirmationResponse(BaseModel):
    status: str = Field(..., description="SUCCESS or INSUFFICIENT_FUNDS")
    success: bool
    message: str
    transaction_id: Optional[int] = None
    amount: float
    previous_balance: float
    remaining_balance: float
    deducted: bool


class TopUpRequest(BaseModel):
    amount: float = Field(..., gt=0, le=10000000, description="Amount to add to demo balance in INR")

